stages:
  - test
  - build
  - deploy

variables:
  IMAGE_NAME: "spring-petclinic"
  IMAGE_TAG: "4.0"
  ECR_REPOSITORY_SERVER: "$AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_NAME"

gitleaks:
  stage: test
  image:
    name: zricethezav/gitleaks
    entrypoint: [""]
  script:
    # source path will be current directory as gitlab-ci loads the application code into every container for every job.
    - gitleaks detect --verbose --source . -f json -r gitleaks-report.json
  allow_failure: true
  artifacts:
    when: always
    expire_in: 15 mins
    paths:
      - gitleaks-report.json
  rules:
    - when: never

semgrep:
  stage: test
  image: semgrep/semgrep
  variables:
    SEMGREP_RULES: p/java
  script:
    - semgrep ci --json --json-output=semgrep-report.json
  allow_failure: true
  artifacts:
    when: always
    expire_in: 15 mins
    paths:
      - semgrep-report.json
  rules:
    - when: never

sca:
  stage: test
  variables:
    NVD_API_KEY: "37a263bf-6f81-465b-9f46-1a5ec67c9347"
  image:
    name: owasp/dependency-check:latest
    entrypoint: [""]
  before_script:
    - ls -al /usr/share/dependency-check/bin/dependency-check.sh
    - mkdir -p dependency-check-data
  script:
    - /usr/share/dependency-check/bin/dependency-check.sh -s . -f JSON -o sca-report --data dependency-check-data --nvdApiKey $NVD_API_KEY
  after_script:
    - ls -lah dependency-check-data || true
  cache:
    key: dependency-check
    paths:
      - dependency-check-data/
  allow_failure: true
  artifacts:
    when: always
    expire_in: 15 mins
    paths:
      - sca-report/dependency-check-report.json
  rules:
    - when: never


upload_reports:
  stage: test
  image: python
  needs:
    - gitleaks
    - semgrep
    - sca
  when: always
  before_script:
    - pip3 install requests
  script:
    - python3 upload-reports.py gitleaks-report.json
    - python3 upload-reports.py semgrep-report.json
    - python3 upload-reports.py sca-report/dependency-check-report.json
  rules:
    - when: never

build-push-image:
  stage: build
  image: docker:29.2.1
  services:
    - docker:29.2.1-dind
  id_tokens:
    AWS_ID_TOKEN:
      aud: https://gitlab.com
  variables:
    DOCKER_BUILDKIT: 1
    AWS_ROLE_ARN: arn:aws:iam::460469850064:role/gitlab-ci-federated-role
    AWS_WEB_IDENTITY_TOKEN_FILE: /tmp/aws_token
#    AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
#    AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
#    AWS_DEFAULT_REGION: $AWS_DEFAULT_REGION
#    AWS_ACCOUNT_ID: $AWS_ACCOUNT_ID
  before_script:
    - |
    - apk add --no-cache aws-cli
    - echo "Default region $AWS_DEFAULT_REGION, account id $AWS_ACCOUNT_ID"
    - echo "$AWS_ID_TOKEN" > $AWS_WEB_IDENTITY_TOKEN_FILE
    - aws sts get-caller-identity
    - "aws ecr get-login-password | docker login -u AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com"
  script:
    - docker pull $ECR_REPOSITORY_SERVER:$IMAGE_TAG || true
    - docker build --build-arg BUILDKIT_INLINE_CACHE=1 --cache-from $ECR_REPOSITORY_SERVER:$IMAGE_TAG -t $ECR_REPOSITORY_SERVER:$IMAGE_TAG .
    - docker push $ECR_REPOSITORY_SERVER:$IMAGE_TAG


trivy-scan:
  stage: build
  needs:
    - build-push-image
  image: aquasec/trivy:latest
  id_tokens:
    AWS_ID_TOKEN:
      aud: https://gitlab.com
  variables:
    DOCKER_BUILDKIT: 1
    AWS_ROLE_ARN: arn:aws:iam::460469850064:role/gitlab-ci-federated-role
    AWS_WEB_IDENTITY_TOKEN_FILE: /tmp/aws_token
  before_script:
    - |
    - apk add --no-cache aws-cli
    - echo "Default region $AWS_DEFAULT_REGION, account id $AWS_ACCOUNT_ID"
    - echo "$AWS_ID_TOKEN" > $AWS_WEB_IDENTITY_TOKEN_FILE
    - aws sts get-caller-identity
    - "aws ecr get-login-password | docker login -u AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com"
  script:
    - trivy image --exit-code 1 --severity HIGH,CRITICAL $ECR_REPOSITORY_SERVER:$IMAGE_TAG


