stages:
  - test
  - build
  - deploy
  - trigger-downstream-pipeline

variables:
  IMAGE_NAME: "spring-petclinic"
  IMAGE_TAG: "4.0"
  ECR_REPOSITORY_SERVER: "$AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_NAME"

gitleaks:
  stage: test
  image:
    name: zricethezav/gitleaks
    entrypoint: [""]
  script:
    # source path will be current directory as gitlab-ci loads the application code into every container for every job.
    - gitleaks detect --verbose --source . -f json -r gitleaks-report.json
  allow_failure: true
  artifacts:
    when: always
    expire_in: 15 mins
    paths:
      - gitleaks-report.json
  rules:
    - when: never

semgrep:
  stage: test
  image: semgrep/semgrep
  variables:
    SEMGREP_RULES: p/java
  script:
    - semgrep ci --json --json-output=semgrep-report.json
  allow_failure: true
  artifacts:
    when: always
    expire_in: 15 mins
    paths:
      - semgrep-report.json
  rules:
    - when: never

sca:
  stage: test
  variables:
    NVD_API_KEY: "37a263bf-6f81-465b-9f46-1a5ec67c9347"
  image:
    name: owasp/dependency-check:latest
    entrypoint: [""]
  before_script:
    - ls -al /usr/share/dependency-check/bin/dependency-check.sh
    - mkdir -p dependency-check-data
  script:
    - /usr/share/dependency-check/bin/dependency-check.sh -s . -f JSON -o sca-report --data dependency-check-data --nvdApiKey $NVD_API_KEY
  after_script:
    - ls -lah dependency-check-data || true
  cache:
    key: dependency-check
    paths:
      - dependency-check-data/
  allow_failure: true
  artifacts:
    when: always
    expire_in: 15 mins
    paths:
      - sca-report/dependency-check-report.json
  rules:
    - when: never


upload_reports:
  stage: test
  image: python
  needs:
    - gitleaks
    - semgrep
    - sca
  when: always
  before_script:
    - pip3 install requests
  script:
    - python3 upload-reports.py gitleaks-report.json
    - python3 upload-reports.py semgrep-report.json
    - python3 upload-reports.py sca-report/dependency-check-report.json
  rules:
    - when: never

build-push-image:
  stage: build
  image: docker:29.2.1
  services:
    - docker:29.2.1-dind
  variables:
    DOCKER_BUILDKIT: 1
  id_tokens:
    GITLAB_OIDC_TOKEN:
      aud: https://gitlab.com
  before_script:
    - apk add --no-cache aws-cli
    - >
      export $(printf "AWS_ACCESS_KEY_ID=%s AWS_SECRET_ACCESS_KEY=%s AWS_SESSION_TOKEN=%s"
      $(aws sts assume-role-with-web-identity
      --role-arn ${ROLE_ARN}
      --role-session-name "GitLabRunner-${CI_PROJECT_ID}-${CI_PIPELINE_ID}"
      --web-identity-token ${GITLAB_OIDC_TOKEN}
      --duration-seconds 3600
      --query 'Credentials.[AccessKeyId,SecretAccessKey,SessionToken]'
      --output text))
    - aws sts get-caller-identity
    - echo "Default region $AWS_DEFAULT_REGION, account id $AWS_ACCOUNT_ID"
    - "aws ecr get-login-password | docker login -u AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com"
  script:
    - docker pull $ECR_REPOSITORY_SERVER:$IMAGE_TAG || true
    - docker build --build-arg BUILDKIT_INLINE_CACHE=1 --cache-from $ECR_REPOSITORY_SERVER:$IMAGE_TAG -t $ECR_REPOSITORY_SERVER:$IMAGE_TAG .
    - docker push $ECR_REPOSITORY_SERVER:$IMAGE_TAG


trivy-scan:
  stage: build
  needs:
    - build-push-image
  image: docker:29.2.1
  services:
    - docker:29.2.1-dind
  variables:
    DOCKER_BUILDKIT: 1
  id_tokens:
    GITLAB_OIDC_TOKEN:
      aud: https://gitlab.com
  before_script:
    - |
    - apk add --no-cache aws-cli curl python3 py3-pip
    - curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh -s -- -b /usr/local/bin v0.69.3
    - >
      export $(printf "AWS_ACCESS_KEY_ID=%s AWS_SECRET_ACCESS_KEY=%s AWS_SESSION_TOKEN=%s"
      $(aws sts assume-role-with-web-identity
      --role-arn ${ROLE_ARN}
      --role-session-name "GitLabRunner-${CI_PROJECT_ID}-${CI_PIPELINE_ID}"
      --web-identity-token ${GITLAB_OIDC_TOKEN}
      --duration-seconds 3600
      --query 'Credentials.[AccessKeyId,SecretAccessKey,SessionToken]'
      --output text))
    - aws sts get-caller-identity
    - echo "Default region $AWS_DEFAULT_REGION, account id $AWS_ACCOUNT_ID"
    - "aws ecr get-login-password | docker login -u AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com"
  script:
    - trivy image --exit-code 1 --severity HIGH,CRITICAL $ECR_REPOSITORY_SERVER:$IMAGE_TAG
  allow_failure: true

trigger_job:
  stage: trigger-downstream-pipeline
  trigger:
    project: ranjitha-projects/spring-petclinic-gitops.git
    strategy: depend
